# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersons.proto\x12\x07persons\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12-\n\tbirthdate\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"U\n\nConnection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12(\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x16\n\x08PersonId\x12\n\n\x02id\x18\x01 \x01(\t\"\x96\x01\n\x11\x43onnectionRequest\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12.\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x64istance\x18\x04 \x01(\x05\x32\xff\x01\n\x0ePersonsService\x12\x30\n\x0c\x43reatePerson\x12\x0f.persons.Person\x1a\x0f.persons.Person\x12?\n\x12RetrieveAllPersons\x12\x16.google.protobuf.Empty\x1a\x0f.persons.Person0\x01\x12\x34\n\x0eRetrievePerson\x12\x11.persons.PersonId\x1a\x0f.persons.Person\x12\x44\n\x0f\x46indConnections\x12\x1a.persons.ConnectionRequest\x1a\x13.persons.Connection0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'persons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PERSON']._serialized_start=88
  _globals['_PERSON']._serialized_end=184
  _globals['_CONNECTION']._serialized_start=186
  _globals['_CONNECTION']._serialized_end=271
  _globals['_PERSONID']._serialized_start=273
  _globals['_PERSONID']._serialized_end=295
  _globals['_CONNECTIONREQUEST']._serialized_start=298
  _globals['_CONNECTIONREQUEST']._serialized_end=448
  _globals['_PERSONSSERVICE']._serialized_start=451
  _globals['_PERSONSSERVICE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
